colname = read.table("household_power_consumption.txt",sep = ";", nrows = 1,header = TRUE)
data = read.table("household_power_consumption.txt",sep=";",skip=66637,nrows = 2880,col.names = names(colname))
data$Time = paste(data$Date,":",data$Time,sep="")
x = lapply(data$Time,strptime,format="%d/%m/%Y:%H:%M:%S")
t = lapply(x,as.POSIXlt)
t = lapply(t,as.numeric)
png(filename = "plot2.png",width = 480, height = 480, units = "px")
plot(t,data$Global_active_power,type = 'l',pch = 21,ylab = "Global Active Power (kilowatts)",xaxt = "n", xlab = "")
axis(1,labels=c("Thu","Fri","Sat"),at=c(t[[1]],t[[1440]],t[[2880]]))
dev.off()